import { useEffect, useState } from "react";
import { Panel } from "../components/Panel";
import api from "../services/api";

export function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [creating, setCreating] = useState(false);

  async function loadReports() {
    const response = await api.get("/reports");
    setReports(response.data);
  }

  useEffect(() => {
    loadReports();
  }, []);

  async function generateReport() {
    setCreating(true);
    await api.post("/reports");
    await loadReports();
    setCreating(false);
  }

  async function exportPdf(reportId, reportName) {
    const response = await api.get(`/reports/${reportId}/pdf`, { responseType: "blob" });
    const fileUrl = URL.createObjectURL(response.data);
    const link = document.createElement("a");
    link.href = fileUrl;
    link.download = `${reportName}.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(fileUrl);
  }

  return (
    <Panel
      title="Compliance Reports"
      subtitle="Generate and export PDF reports for audits and regulator review"
      action={
        <button
          onClick={generateReport}
          disabled={creating}
          className="rounded-2xl bg-cyber-blue px-4 py-2 text-sm font-medium text-white disabled:opacity-60"
        >
          {creating ? "Generating..." : "Generate Report"}
        </button>
      }
    >
      <div className="space-y-4">
        {reports.map((report) => (
          <div key={report._id} className="rounded-3xl border border-cyber-line bg-slate-950/35 p-5">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <h4 className="text-lg font-semibold text-white">{report.reportName}</h4>
                <p className="mt-1 text-sm text-slate-400">
                  Generated by {report.generatedBy} on {new Date(report.createdAt).toLocaleString()}
                </p>
              </div>
              <button
                onClick={() => exportPdf(report._id, report.reportName)}
                className="rounded-2xl border border-cyber-neon/40 px-4 py-2 text-sm text-cyber-neon"
              >
                Export PDF
              </button>
            </div>
            <div className="mt-4 flex flex-wrap gap-3 text-sm text-slate-300">
              <span className="rounded-full border border-cyber-red/30 bg-cyber-red/10 px-3 py-1">
                Violations: {report.summary.violations}
              </span>
              <span className="rounded-full border border-cyber-amber/30 bg-cyber-amber/10 px-3 py-1 text-cyber-amber">
                Medium Risk: {report.summary.mediumRisk}
              </span>
              <span className="rounded-full border border-cyber-red/30 bg-cyber-red/10 px-3 py-1 text-cyber-red">
                High Risk: {report.summary.highRisk}
              </span>
            </div>
            <pre className="mt-4 whitespace-pre-wrap rounded-2xl border border-cyber-line bg-cyber-panelAlt/50 p-4 text-xs text-slate-300">
              {JSON.stringify(report.summary, null, 2)}
            </pre>
          </div>
        ))}
      </div>
    </Panel>
  );
}
