import PDFDocument from "pdfkit";

export function buildSummary(records) {
  const summary = {
    totalRecords: records.length,
    compliant: 0,
    violations: 0,
    lowRisk: 0,
    mediumRisk: 0,
    highRisk: 0
  };

  for (const record of records) {
    if (record.complianceStatus === "Compliant") summary.compliant += 1;
    if (record.complianceStatus === "Violation") summary.violations += 1;
    if (record.riskScore === "Low") summary.lowRisk += 1;
    if (record.riskScore === "Medium") summary.mediumRisk += 1;
    if (record.riskScore === "High") summary.highRisk += 1;
  }

  return summary;
}

export function renderReportPdf(report, res) {
  const doc = new PDFDocument({ margin: 40 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=${report.reportName}.pdf`);
  doc.pipe(res);

  doc.fontSize(22).text("IntrusionX Compliance Report", { underline: true });
  doc.moveDown();
  doc.fontSize(12).text(`Generated By: ${report.generatedBy}`);
  doc.text(`Generated At: ${new Date(report.createdAt).toLocaleString()}`);
  doc.moveDown();
  doc.fontSize(16).text("Summary");
  Object.entries(report.summary).forEach(([key, value]) => {
    doc.fontSize(12).text(`${key}: ${value}`);
  });
  doc.moveDown();
  doc.fontSize(16).text("Findings");
  report.findings.forEach((finding, index) => {
    doc.fontSize(12).text(
      `${index + 1}. ${finding.recordId} | ${finding.complianceStatus} | ${finding.riskScore}`
    );
  });
  doc.end();
}
